### ISSUE TITLE
Documented nescent maven repo is offline

### ISSUE THREAD

**Issue by ianmcorvidae** [nexml/nexml.java#12]
In doing a leiningen build, attempting to download dependencies:

```
Could not transfer artifact org.nexml.model:nexml:pom:1.5-SNAPSHOT from/to nexml (http://nexml-dev.nescent.org/.m2/repository): Connect to nexml-dev.nescent.org:80 [nexml-dev.nescent.org/67.159.80.254] failed: Connection refused
```

I see talk of moving away from nescent -- is there an alternate source for this information? Any progress on #8, perhaps?

**Comment by rvosa** [comment]
The maven repo has moved to http://nexml.github.io/maven/repository
