### ISSUE TITLE
Test files missing

### ISSUE THREAD

**Issue by daisieh** [nexml/nexml.java#17]
@rvosa: The test classes reference a few sample files that don't seem to be present in the repo:
/examples/meta_types.xml
/examples/characters.xml
/examples/trees.xml
/examples/02_dogfish_no_taxrefs.xml

They seem to be mostly located in your $NEXML_ROOT, which was at `/Users/rvosa/Dropbox/documents/projects/current/nexml/src/nexml/trunk/nexml` back when you wrote the cases. Can you find them and add them to the repo?

**Comment by rvosa** [comment]
They have been factored out by @yeban to a separate repo that contains just "core" NeXML files, not code in any non-XML language. The rationale is that all languages can then use the same test files without created a monster repo with all the languages in it. The example files are here: https://github.com/nexml/nexml/tree/master/examples

**Comment by daisieh** [comment]
Cool. I made a pull request to get the example files directly from that repo instead of having to be contained in this one. https://github.com/nexml/nexml.java/pull/18

**Comment by rvosa** [comment]
I've given you direct commit access, maybe that's easiest?

**Comment by daisieh** [comment]
Thanks! I'll merge that PR then.
