### ISSUE TITLE
Could you add licence file?

### ISSUE THREAD

**Issue by PavelAAlexeev** [nexml/nexml.java#22]
Hello! 
This package is used in https://github.com/danielhuson/dendroscope3 project which is added at DebianMed packages(https://blends.debian.org/med/tasks/). So could you please add the license to the NeXML to allow (or not) to use it in Debian? 
Thank you!

**Comment by rvosa** [comment]
Good suggestion, thanks. If we use an academic license such as the MIT one, would that work for you?

**Comment by PavelAAlexeev** [comment]
I think yes. Thanks a lot!

**Comment by rvosa** [comment]
Done: f8cb34ca67f7c194ef0dccf4e387cd2926d09948
